### ISSUE TITLE
Please expose the "width" and "height" properties on your Text plugins.

### ISSUE THREAD

**Issue by thewaver** [rexrainbow/phaser4-rex-plugins#2]
Title says it all.
Thank you!

**Comment by rexrainbow** [comment]
My plugins of phaser4 had not been upgraded to compact with latest phaser4, therefore I will assume that the plugins won't work currently.

**Comment by thewaver** [comment]
Sorry for the late response. I did not get notified.
I am on phaser 3.55.2 - not on phaser 4. I couldn't find the correct GH page for the V3 of your plugins.
Feel free to close this issue (and redirect me if I'm not in the right place).

**Comment by rexrainbow** [comment]
[Issue page of my phaser3 plugins](https://github.com/rexrainbow/phaser3-rex-notes/issues)
