### ISSUE TITLE
[VirtualJoystick] Can VirtualJoystick and Button coexist?

### ISSUE THREAD

**Issue by desmofab** [rexrainbow/phaser4-rex-plugins#3]
Hi, first of all thanks for all these amazing plugins and for all the time spent on them, I really appreciate that.
I've a just a simple question about VirtualJoystick plugin:
Using Phaser3, I was trying to implement a virtualjoystick plugin (player move), and a simple fire button.
They actually work like a charm, but only if I press one of them individually. When playing on a mobile device, if I keep the joystick pressed (because of moving), the fire button doesn't work. I've to release the thumb on virtualjoystick before, either the joystick or the button I mean. Trying to debug using devtools on Chrome, it seems that the `click` event on the button, doesn't fire at all if you are moving the joystick.
This is my code:
``` 
import Button from 'phaser3-rex-plugins/plugins/button.js';
import VirtualJoystick from 'phaser3-rex-plugins/plugins/virtualjoystick.js';

export class Player extends Phaser.Physics.Arcade.Image {
...

createJoyStick() {
  this.joystick = new VirtualJoystick(this.scene, {
    x: 100,
    y: 500,
    radius: 50,
  });
}

...

createFireButton() {
  const button = this.scene.add.circle(700, 500, 30).setStrokeStyle(2, 0x1a65ac)
  this.fireButton = new Button(button);
  this.fireButton.on('click', () => {
    //... fire!
  });
}
```

and from my package.json
```
...
"phaser": "^3.55.2",
"phaser3-rex-plugins": "^1.1.69",
...
```
I can understand if you won't help me, don't worry, but thank you anyway.

**Comment by rexrainbow** [comment]
Please post this issue on phaser3.

**Comment by rexrainbow** [comment]
To get more [touch pointers](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/touchevents/#multi-touch)

**Comment by desmofab** [comment]
Ops, sorry my bad.
I post the issue on the other repo.
Thnks
